# MkDocs configuration file

# Required: Name of the site
site_name: 'OT.pentest'

# Optional but recommended: Directory where the documentation source files are located
docs_dir: 'docs'

# Other optional configurations can be added below
# For example, specifying a theme, extensions, or plugins

# Uncomment and set a theme if needed (e.g., 'mkdocs', 'readthedocs')
# theme:
#   name: 'mkdocs'

# Uncomment and add extensions if needed
# markdown_extensions:
#   - toc:
#       permalink: true
#   - tables
#   - admonition

# Uncomment and add plugins if needed
# plugins:
#   - search
#   - minify:
#       minify_html: true

# Build settings
# Uncomment to set specific build options
# strict: true
# fail_on_warning: false
